### ISSUE TITLE
Any planned updates?

### ISSUE THREAD

**Issue by samsebastien** [antoinevastel/fpscanner#12]
I found this to be an awesome tool for detection when I last needed it back in early 2019, but it seems like many of the tests are now bypassed... 

Are there any plans to update with new tests?

Thanks!

**Comment by antoinevastel** [comment]
Hi, due to my current professional situation I'm not going to update this
library before a while.

Antoine

Le ven. 24 juil. 2020 à 01:35, Sam Sébastien <notifications@github.com> a
écrit :
