### ISSUE TITLE
webdriver Firefox 48 to 60 versions questions

### ISSUE THREAD

**Issue by ghost** [antoinevastel/fpscanner#7]
I read your Fingerprint identification method and wrote it very well.
But there is a question I would like to ask, this method of yours does not recognize the webdriver-driven Firefox from the 48-60 version.
Is there any way to identify these versions of Firefox's webdriver?
Thank you

**Comment by antoinevastel** [comment]
Do you have a fingerprint collected on such automated browser?

**Comment by antoinevastel** [comment]
No, but I can have a look at it this week end.

**Comment by antoinevastel** [comment]
I don't have an old version of Firefox on my computer, only version 64.
I compared a normal Firefox against a Firefox automated with Selenium in non-headless mode.
I obtain the following diff:

```diff
28c28
<    "historyLength":2,
---
>    "historyLength":1,
30a31,32
>       "fr",
>       "fr-FR",
34c36
<    "language":"en-US",
---
>    "language":"fr",
38,42c40,44
<       "wInnerHeight":804,
<       "wOuterHeight":900,
<       "wOuterWidth":1440,
<       "wInnerWidth":1440,
<       "wScreenX":0,
---
>       "wInnerHeight":758,
>       "wOuterHeight":832,
>       "wOuterWidth":1280,
>       "wInnerWidth":1280,
>       "wScreenX":4,
45c47
<       "cWidth":1440,
---
>       "cWidth":1280,
154c156
<    "webDriverValue":false,
---
>    "webDriverValue":true,
168c170
<       "depth":107109,
---
>       "depth":103949,
```
